// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// CreateSocialAccountInput is used for create SocialAccount object.
/// Input was generated by ent.
public struct CreateSocialAccountInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    email: String,
    platform: GraphQLEnum<SocialAccountPlatform>,
    socialAccountOwnerID: GraphQLNullable<ID> = nil
  ) {
    __data = InputDict([
      "email": email,
      "platform": platform,
      "socialAccountOwnerID": socialAccountOwnerID
    ])
  }

  public var email: String {
    get { __data["email"] }
    set { __data["email"] = newValue }
  }

  public var platform: GraphQLEnum<SocialAccountPlatform> {
    get { __data["platform"] }
    set { __data["platform"] = newValue }
  }

  public var socialAccountOwnerID: GraphQLNullable<ID> {
    get { __data["socialAccountOwnerID"] }
    set { __data["socialAccountOwnerID"] = newValue }
  }
}
