// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// CreateCitizenInput is used for create Citizen object.
/// Input was generated by ent.
public struct CreateCitizenInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    countryName: String,
    code: String,
    citizenOwnerID: GraphQLNullable<ID> = nil
  ) {
    __data = InputDict([
      "countryName": countryName,
      "code": code,
      "citizenOwnerID": citizenOwnerID
    ])
  }

  public var countryName: String {
    get { __data["countryName"] }
    set { __data["countryName"] = newValue }
  }

  public var code: String {
    get { __data["code"] }
    set { __data["code"] = newValue }
  }

  public var citizenOwnerID: GraphQLNullable<ID> {
    get { __data["citizenOwnerID"] }
    set { __data["citizenOwnerID"] = newValue }
  }
}
