// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// CreateLifePhotoInput is used for create LifePhoto object.
/// Input was generated by ent.
public struct CreateLifePhotoInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    contentURL: String,
    caption: GraphQLNullable<String> = nil,
    position: Int,
    ratio: Int,
    scale: Double,
    offsetX: Double,
    offsetY: Double,
    lifePhotoOwnerID: GraphQLNullable<ID> = nil
  ) {
    __data = InputDict([
      "contentURL": contentURL,
      "caption": caption,
      "position": position,
      "ratio": ratio,
      "scale": scale,
      "offsetX": offsetX,
      "offsetY": offsetY,
      "lifePhotoOwnerID": lifePhotoOwnerID
    ])
  }

  public var contentURL: String {
    get { __data["contentURL"] }
    set { __data["contentURL"] = newValue }
  }

  public var caption: GraphQLNullable<String> {
    get { __data["caption"] }
    set { __data["caption"] = newValue }
  }

  public var position: Int {
    get { __data["position"] }
    set { __data["position"] = newValue }
  }

  public var ratio: Int {
    get { __data["ratio"] }
    set { __data["ratio"] = newValue }
  }

  public var scale: Double {
    get { __data["scale"] }
    set { __data["scale"] = newValue }
  }

  public var offsetX: Double {
    get { __data["offsetX"] }
    set { __data["offsetX"] = newValue }
  }

  public var offsetY: Double {
    get { __data["offsetY"] }
    set { __data["offsetY"] = newValue }
  }

  public var lifePhotoOwnerID: GraphQLNullable<ID> {
    get { __data["lifePhotoOwnerID"] }
    set { __data["lifePhotoOwnerID"] = newValue }
  }
}
