// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// CreateEthnicityInput is used for create Ethnicity object.
/// Input was generated by ent.
public struct CreateEthnicityInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    ethnicityType: GraphQLEnum<EthnicityEthnicityType>,
    ethnicityOwnerID: GraphQLNullable<ID> = nil
  ) {
    __data = InputDict([
      "ethnicityType": ethnicityType,
      "ethnicityOwnerID": ethnicityOwnerID
    ])
  }

  public var ethnicityType: GraphQLEnum<EthnicityEthnicityType> {
    get { __data["ethnicityType"] }
    set { __data["ethnicityType"] = newValue }
  }

  public var ethnicityOwnerID: GraphQLNullable<ID> {
    get { __data["ethnicityOwnerID"] }
    set { __data["ethnicityOwnerID"] = newValue }
  }
}
