// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// CreateUserInput is used for create User object.
/// Input was generated by ent.
public struct CreateUserInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    createdAt: GraphQLNullable<Time> = nil,
    updatedAt: GraphQLNullable<Time> = nil,
    email: String,
    password: GraphQLNullable<String> = nil,
    username: String,
    firstName: GraphQLNullable<String> = nil,
    lastName: GraphQLNullable<String> = nil,
    dateOfBirth: Time,
    gender: GraphQLEnum<UserGender>,
    profilePictureURL: GraphQLNullable<String> = nil,
    voiceContentURL: GraphQLNullable<String> = nil,
    selfIntro: GraphQLNullable<String> = nil,
    longitude: Double,
    latitude: Double,
    country: GraphQLNullable<String> = nil,
    administrativeArea: GraphQLNullable<String> = nil,
    googleConnect: GraphQLNullable<Bool> = nil,
    facebookConnect: GraphQLNullable<Bool> = nil,
    appleConnect: GraphQLNullable<Bool> = nil,
    premium: GraphQLNullable<Bool> = nil,
    citizenIDs: GraphQLNullable<[ID]> = nil,
    goalIDs: GraphQLNullable<[ID]> = nil,
    matchIDs: GraphQLNullable<[ID]> = nil,
    likedByIDs: GraphQLNullable<[ID]> = nil,
    likeIDs: GraphQLNullable<[ID]> = nil,
    ethnicityIDs: GraphQLNullable<[ID]> = nil,
    socialAccountIDs: GraphQLNullable<[ID]> = nil,
    lifePhotoIDs: GraphQLNullable<[ID]> = nil,
    createUserCitizen: GraphQLNullable<[CreateCitizenInput]> = nil,
    createUserGoal: GraphQLNullable<[CreateGoalInput]> = nil,
    createUserEthnicity: GraphQLNullable<[CreateEthnicityInput]> = nil,
    createUserSocialAccount: CreateSocialAccountInput,
    createUserLifePhoto: CreateLifePhotoInput
  ) {
    __data = InputDict([
      "createdAt": createdAt,
      "updatedAt": updatedAt,
      "email": email,
      "password": password,
      "username": username,
      "firstName": firstName,
      "lastName": lastName,
      "dateOfBirth": dateOfBirth,
      "gender": gender,
      "profilePictureURL": profilePictureURL,
      "voiceContentURL": voiceContentURL,
      "selfIntro": selfIntro,
      "longitude": longitude,
      "latitude": latitude,
      "country": country,
      "administrativeArea": administrativeArea,
      "googleConnect": googleConnect,
      "facebookConnect": facebookConnect,
      "appleConnect": appleConnect,
      "premium": premium,
      "citizenIDs": citizenIDs,
      "goalIDs": goalIDs,
      "matchIDs": matchIDs,
      "likedByIDs": likedByIDs,
      "likeIDs": likeIDs,
      "ethnicityIDs": ethnicityIDs,
      "socialAccountIDs": socialAccountIDs,
      "lifePhotoIDs": lifePhotoIDs,
      "createUserCitizen": createUserCitizen,
      "createUserGoal": createUserGoal,
      "createUserEthnicity": createUserEthnicity,
      "createUserSocialAccount": createUserSocialAccount,
      "createUserLifePhoto": createUserLifePhoto
    ])
  }

  public var createdAt: GraphQLNullable<Time> {
    get { __data["createdAt"] }
    set { __data["createdAt"] = newValue }
  }

  public var updatedAt: GraphQLNullable<Time> {
    get { __data["updatedAt"] }
    set { __data["updatedAt"] = newValue }
  }

  public var email: String {
    get { __data["email"] }
    set { __data["email"] = newValue }
  }

  public var password: GraphQLNullable<String> {
    get { __data["password"] }
    set { __data["password"] = newValue }
  }

  public var username: String {
    get { __data["username"] }
    set { __data["username"] = newValue }
  }

  public var firstName: GraphQLNullable<String> {
    get { __data["firstName"] }
    set { __data["firstName"] = newValue }
  }

  public var lastName: GraphQLNullable<String> {
    get { __data["lastName"] }
    set { __data["lastName"] = newValue }
  }

  public var dateOfBirth: Time {
    get { __data["dateOfBirth"] }
    set { __data["dateOfBirth"] = newValue }
  }

  public var gender: GraphQLEnum<UserGender> {
    get { __data["gender"] }
    set { __data["gender"] = newValue }
  }

  public var profilePictureURL: GraphQLNullable<String> {
    get { __data["profilePictureURL"] }
    set { __data["profilePictureURL"] = newValue }
  }

  public var voiceContentURL: GraphQLNullable<String> {
    get { __data["voiceContentURL"] }
    set { __data["voiceContentURL"] = newValue }
  }

  public var selfIntro: GraphQLNullable<String> {
    get { __data["selfIntro"] }
    set { __data["selfIntro"] = newValue }
  }

  public var longitude: Double {
    get { __data["longitude"] }
    set { __data["longitude"] = newValue }
  }

  public var latitude: Double {
    get { __data["latitude"] }
    set { __data["latitude"] = newValue }
  }

  public var country: GraphQLNullable<String> {
    get { __data["country"] }
    set { __data["country"] = newValue }
  }

  public var administrativeArea: GraphQLNullable<String> {
    get { __data["administrativeArea"] }
    set { __data["administrativeArea"] = newValue }
  }

  public var googleConnect: GraphQLNullable<Bool> {
    get { __data["googleConnect"] }
    set { __data["googleConnect"] = newValue }
  }

  public var facebookConnect: GraphQLNullable<Bool> {
    get { __data["facebookConnect"] }
    set { __data["facebookConnect"] = newValue }
  }

  public var appleConnect: GraphQLNullable<Bool> {
    get { __data["appleConnect"] }
    set { __data["appleConnect"] = newValue }
  }

  public var premium: GraphQLNullable<Bool> {
    get { __data["premium"] }
    set { __data["premium"] = newValue }
  }

  public var citizenIDs: GraphQLNullable<[ID]> {
    get { __data["citizenIDs"] }
    set { __data["citizenIDs"] = newValue }
  }

  public var goalIDs: GraphQLNullable<[ID]> {
    get { __data["goalIDs"] }
    set { __data["goalIDs"] = newValue }
  }

  public var matchIDs: GraphQLNullable<[ID]> {
    get { __data["matchIDs"] }
    set { __data["matchIDs"] = newValue }
  }

  public var likedByIDs: GraphQLNullable<[ID]> {
    get { __data["likedByIDs"] }
    set { __data["likedByIDs"] = newValue }
  }

  public var likeIDs: GraphQLNullable<[ID]> {
    get { __data["likeIDs"] }
    set { __data["likeIDs"] = newValue }
  }

  public var ethnicityIDs: GraphQLNullable<[ID]> {
    get { __data["ethnicityIDs"] }
    set { __data["ethnicityIDs"] = newValue }
  }

  public var socialAccountIDs: GraphQLNullable<[ID]> {
    get { __data["socialAccountIDs"] }
    set { __data["socialAccountIDs"] = newValue }
  }

  public var lifePhotoIDs: GraphQLNullable<[ID]> {
    get { __data["lifePhotoIDs"] }
    set { __data["lifePhotoIDs"] = newValue }
  }

  public var createUserCitizen: GraphQLNullable<[CreateCitizenInput]> {
    get { __data["createUserCitizen"] }
    set { __data["createUserCitizen"] = newValue }
  }

  public var createUserGoal: GraphQLNullable<[CreateGoalInput]> {
    get { __data["createUserGoal"] }
    set { __data["createUserGoal"] = newValue }
  }

  public var createUserEthnicity: GraphQLNullable<[CreateEthnicityInput]> {
    get { __data["createUserEthnicity"] }
    set { __data["createUserEthnicity"] = newValue }
  }

  public var createUserSocialAccount: CreateSocialAccountInput {
    get { __data["createUserSocialAccount"] }
    set { __data["createUserSocialAccount"] = newValue }
  }

  public var createUserLifePhoto: CreateLifePhotoInput {
    get { __data["createUserLifePhoto"] }
    set { __data["createUserLifePhoto"] = newValue }
  }
}
