// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// CreateGoalInput is used for create Goal object.
/// Input was generated by ent.
public struct CreateGoalInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    goalType: GraphQLEnum<GoalGoalType>,
    goalOwnerID: GraphQLNullable<ID> = nil
  ) {
    __data = InputDict([
      "goalType": goalType,
      "goalOwnerID": goalOwnerID
    ])
  }

  public var goalType: GraphQLEnum<GoalGoalType> {
    get { __data["goalType"] }
    set { __data["goalType"] = newValue }
  }

  public var goalOwnerID: GraphQLNullable<ID> {
    get { __data["goalOwnerID"] }
    set { __data["goalOwnerID"] = newValue }
  }
}
