// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// UpdateLifePhotoInput is used for update LifePhoto object.
/// Input was generated by ent.
public struct UpdateLifePhotoInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    contentURL: GraphQLNullable<String> = nil,
    caption: GraphQLNullable<String> = nil,
    clearCaption: GraphQLNullable<Bool> = nil,
    position: GraphQLNullable<Int> = nil,
    scale: GraphQLNullable<Double> = nil,
    offsetX: GraphQLNullable<Double> = nil,
    offsetY: GraphQLNullable<Double> = nil,
    lifePhotoOwnerID: GraphQLNullable<ID> = nil,
    clearLifePhotoOwner: GraphQLNullable<Bool> = nil
  ) {
    __data = InputDict([
      "contentURL": contentURL,
      "caption": caption,
      "clearCaption": clearCaption,
      "position": position,
      "scale": scale,
      "offsetX": offsetX,
      "offsetY": offsetY,
      "lifePhotoOwnerID": lifePhotoOwnerID,
      "clearLifePhotoOwner": clearLifePhotoOwner
    ])
  }

  public var contentURL: GraphQLNullable<String> {
    get { __data["contentURL"] }
    set { __data["contentURL"] = newValue }
  }

  public var caption: GraphQLNullable<String> {
    get { __data["caption"] }
    set { __data["caption"] = newValue }
  }

  public var clearCaption: GraphQLNullable<Bool> {
    get { __data["clearCaption"] }
    set { __data["clearCaption"] = newValue }
  }

  public var position: GraphQLNullable<Int> {
    get { __data["position"] }
    set { __data["position"] = newValue }
  }

  public var scale: GraphQLNullable<Double> {
    get { __data["scale"] }
    set { __data["scale"] = newValue }
  }

  public var offsetX: GraphQLNullable<Double> {
    get { __data["offsetX"] }
    set { __data["offsetX"] = newValue }
  }

  public var offsetY: GraphQLNullable<Double> {
    get { __data["offsetY"] }
    set { __data["offsetY"] = newValue }
  }

  public var lifePhotoOwnerID: GraphQLNullable<ID> {
    get { __data["lifePhotoOwnerID"] }
    set { __data["lifePhotoOwnerID"] = newValue }
  }

  public var clearLifePhotoOwner: GraphQLNullable<Bool> {
    get { __data["clearLifePhotoOwner"] }
    set { __data["clearLifePhotoOwner"] = newValue }
  }
}
