// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// UpdateUserInput is used for update User object.
/// Input was generated by ent.
public struct UpdateUserInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    updatedAt: GraphQLNullable<Time> = nil,
    email: GraphQLNullable<String> = nil,
    password: GraphQLNullable<String> = nil,
    clearPassword: GraphQLNullable<Bool> = nil,
    username: GraphQLNullable<String> = nil,
    firstName: GraphQLNullable<String> = nil,
    clearFirstName: GraphQLNullable<Bool> = nil,
    lastName: GraphQLNullable<String> = nil,
    clearLastName: GraphQLNullable<Bool> = nil,
    dateOfBirth: GraphQLNullable<Time> = nil,
    gender: GraphQLNullable<GraphQLEnum<UserGender>> = nil,
    profilePictureURL: GraphQLNullable<String> = nil,
    clearProfilePictureURL: GraphQLNullable<Bool> = nil,
    voiceContentURL: GraphQLNullable<String> = nil,
    clearVoiceContentURL: GraphQLNullable<Bool> = nil,
    selfIntro: GraphQLNullable<String> = nil,
    clearSelfIntro: GraphQLNullable<Bool> = nil,
    longitude: GraphQLNullable<Double> = nil,
    latitude: GraphQLNullable<Double> = nil,
    country: GraphQLNullable<String> = nil,
    clearCountry: GraphQLNullable<Bool> = nil,
    administrativeArea: GraphQLNullable<String> = nil,
    clearAdministrativeArea: GraphQLNullable<Bool> = nil,
    googleConnect: GraphQLNullable<Bool> = nil,
    facebookConnect: GraphQLNullable<Bool> = nil,
    appleConnect: GraphQLNullable<Bool> = nil,
    premium: GraphQLNullable<Bool> = nil,
    addCitizenIDs: GraphQLNullable<[ID]> = nil,
    removeCitizenIDs: GraphQLNullable<[ID]> = nil,
    clearCitizen: GraphQLNullable<Bool> = nil,
    addGoalIDs: GraphQLNullable<[ID]> = nil,
    removeGoalIDs: GraphQLNullable<[ID]> = nil,
    clearGoal: GraphQLNullable<Bool> = nil,
    addMatchIDs: GraphQLNullable<[ID]> = nil,
    removeMatchIDs: GraphQLNullable<[ID]> = nil,
    clearMatch: GraphQLNullable<Bool> = nil,
    addLikedByIDs: GraphQLNullable<[ID]> = nil,
    removeLikedByIDs: GraphQLNullable<[ID]> = nil,
    clearLikedBy: GraphQLNullable<Bool> = nil,
    addLikeIDs: GraphQLNullable<[ID]> = nil,
    removeLikeIDs: GraphQLNullable<[ID]> = nil,
    clearLike: GraphQLNullable<Bool> = nil,
    addEthnicityIDs: GraphQLNullable<[ID]> = nil,
    removeEthnicityIDs: GraphQLNullable<[ID]> = nil,
    clearEthnicity: GraphQLNullable<Bool> = nil,
    addSocialAccountIDs: GraphQLNullable<[ID]> = nil,
    removeSocialAccountIDs: GraphQLNullable<[ID]> = nil,
    clearSocialAccount: GraphQLNullable<Bool> = nil,
    addLifePhotoIDs: GraphQLNullable<[ID]> = nil,
    removeLifePhotoIDs: GraphQLNullable<[ID]> = nil,
    clearLifePhoto: GraphQLNullable<Bool> = nil
  ) {
    __data = InputDict([
      "updatedAt": updatedAt,
      "email": email,
      "password": password,
      "clearPassword": clearPassword,
      "username": username,
      "firstName": firstName,
      "clearFirstName": clearFirstName,
      "lastName": lastName,
      "clearLastName": clearLastName,
      "dateOfBirth": dateOfBirth,
      "gender": gender,
      "profilePictureURL": profilePictureURL,
      "clearProfilePictureURL": clearProfilePictureURL,
      "voiceContentURL": voiceContentURL,
      "clearVoiceContentURL": clearVoiceContentURL,
      "selfIntro": selfIntro,
      "clearSelfIntro": clearSelfIntro,
      "longitude": longitude,
      "latitude": latitude,
      "country": country,
      "clearCountry": clearCountry,
      "administrativeArea": administrativeArea,
      "clearAdministrativeArea": clearAdministrativeArea,
      "googleConnect": googleConnect,
      "facebookConnect": facebookConnect,
      "appleConnect": appleConnect,
      "premium": premium,
      "addCitizenIDs": addCitizenIDs,
      "removeCitizenIDs": removeCitizenIDs,
      "clearCitizen": clearCitizen,
      "addGoalIDs": addGoalIDs,
      "removeGoalIDs": removeGoalIDs,
      "clearGoal": clearGoal,
      "addMatchIDs": addMatchIDs,
      "removeMatchIDs": removeMatchIDs,
      "clearMatch": clearMatch,
      "addLikedByIDs": addLikedByIDs,
      "removeLikedByIDs": removeLikedByIDs,
      "clearLikedBy": clearLikedBy,
      "addLikeIDs": addLikeIDs,
      "removeLikeIDs": removeLikeIDs,
      "clearLike": clearLike,
      "addEthnicityIDs": addEthnicityIDs,
      "removeEthnicityIDs": removeEthnicityIDs,
      "clearEthnicity": clearEthnicity,
      "addSocialAccountIDs": addSocialAccountIDs,
      "removeSocialAccountIDs": removeSocialAccountIDs,
      "clearSocialAccount": clearSocialAccount,
      "addLifePhotoIDs": addLifePhotoIDs,
      "removeLifePhotoIDs": removeLifePhotoIDs,
      "clearLifePhoto": clearLifePhoto
    ])
  }

  public var updatedAt: GraphQLNullable<Time> {
    get { __data["updatedAt"] }
    set { __data["updatedAt"] = newValue }
  }

  public var email: GraphQLNullable<String> {
    get { __data["email"] }
    set { __data["email"] = newValue }
  }

  public var password: GraphQLNullable<String> {
    get { __data["password"] }
    set { __data["password"] = newValue }
  }

  public var clearPassword: GraphQLNullable<Bool> {
    get { __data["clearPassword"] }
    set { __data["clearPassword"] = newValue }
  }

  public var username: GraphQLNullable<String> {
    get { __data["username"] }
    set { __data["username"] = newValue }
  }

  public var firstName: GraphQLNullable<String> {
    get { __data["firstName"] }
    set { __data["firstName"] = newValue }
  }

  public var clearFirstName: GraphQLNullable<Bool> {
    get { __data["clearFirstName"] }
    set { __data["clearFirstName"] = newValue }
  }

  public var lastName: GraphQLNullable<String> {
    get { __data["lastName"] }
    set { __data["lastName"] = newValue }
  }

  public var clearLastName: GraphQLNullable<Bool> {
    get { __data["clearLastName"] }
    set { __data["clearLastName"] = newValue }
  }

  public var dateOfBirth: GraphQLNullable<Time> {
    get { __data["dateOfBirth"] }
    set { __data["dateOfBirth"] = newValue }
  }

  public var gender: GraphQLNullable<GraphQLEnum<UserGender>> {
    get { __data["gender"] }
    set { __data["gender"] = newValue }
  }

  public var profilePictureURL: GraphQLNullable<String> {
    get { __data["profilePictureURL"] }
    set { __data["profilePictureURL"] = newValue }
  }

  public var clearProfilePictureURL: GraphQLNullable<Bool> {
    get { __data["clearProfilePictureURL"] }
    set { __data["clearProfilePictureURL"] = newValue }
  }

  public var voiceContentURL: GraphQLNullable<String> {
    get { __data["voiceContentURL"] }
    set { __data["voiceContentURL"] = newValue }
  }

  public var clearVoiceContentURL: GraphQLNullable<Bool> {
    get { __data["clearVoiceContentURL"] }
    set { __data["clearVoiceContentURL"] = newValue }
  }

  public var selfIntro: GraphQLNullable<String> {
    get { __data["selfIntro"] }
    set { __data["selfIntro"] = newValue }
  }

  public var clearSelfIntro: GraphQLNullable<Bool> {
    get { __data["clearSelfIntro"] }
    set { __data["clearSelfIntro"] = newValue }
  }

  public var longitude: GraphQLNullable<Double> {
    get { __data["longitude"] }
    set { __data["longitude"] = newValue }
  }

  public var latitude: GraphQLNullable<Double> {
    get { __data["latitude"] }
    set { __data["latitude"] = newValue }
  }

  public var country: GraphQLNullable<String> {
    get { __data["country"] }
    set { __data["country"] = newValue }
  }

  public var clearCountry: GraphQLNullable<Bool> {
    get { __data["clearCountry"] }
    set { __data["clearCountry"] = newValue }
  }

  public var administrativeArea: GraphQLNullable<String> {
    get { __data["administrativeArea"] }
    set { __data["administrativeArea"] = newValue }
  }

  public var clearAdministrativeArea: GraphQLNullable<Bool> {
    get { __data["clearAdministrativeArea"] }
    set { __data["clearAdministrativeArea"] = newValue }
  }

  public var googleConnect: GraphQLNullable<Bool> {
    get { __data["googleConnect"] }
    set { __data["googleConnect"] = newValue }
  }

  public var facebookConnect: GraphQLNullable<Bool> {
    get { __data["facebookConnect"] }
    set { __data["facebookConnect"] = newValue }
  }

  public var appleConnect: GraphQLNullable<Bool> {
    get { __data["appleConnect"] }
    set { __data["appleConnect"] = newValue }
  }

  public var premium: GraphQLNullable<Bool> {
    get { __data["premium"] }
    set { __data["premium"] = newValue }
  }

  public var addCitizenIDs: GraphQLNullable<[ID]> {
    get { __data["addCitizenIDs"] }
    set { __data["addCitizenIDs"] = newValue }
  }

  public var removeCitizenIDs: GraphQLNullable<[ID]> {
    get { __data["removeCitizenIDs"] }
    set { __data["removeCitizenIDs"] = newValue }
  }

  public var clearCitizen: GraphQLNullable<Bool> {
    get { __data["clearCitizen"] }
    set { __data["clearCitizen"] = newValue }
  }

  public var addGoalIDs: GraphQLNullable<[ID]> {
    get { __data["addGoalIDs"] }
    set { __data["addGoalIDs"] = newValue }
  }

  public var removeGoalIDs: GraphQLNullable<[ID]> {
    get { __data["removeGoalIDs"] }
    set { __data["removeGoalIDs"] = newValue }
  }

  public var clearGoal: GraphQLNullable<Bool> {
    get { __data["clearGoal"] }
    set { __data["clearGoal"] = newValue }
  }

  public var addMatchIDs: GraphQLNullable<[ID]> {
    get { __data["addMatchIDs"] }
    set { __data["addMatchIDs"] = newValue }
  }

  public var removeMatchIDs: GraphQLNullable<[ID]> {
    get { __data["removeMatchIDs"] }
    set { __data["removeMatchIDs"] = newValue }
  }

  public var clearMatch: GraphQLNullable<Bool> {
    get { __data["clearMatch"] }
    set { __data["clearMatch"] = newValue }
  }

  public var addLikedByIDs: GraphQLNullable<[ID]> {
    get { __data["addLikedByIDs"] }
    set { __data["addLikedByIDs"] = newValue }
  }

  public var removeLikedByIDs: GraphQLNullable<[ID]> {
    get { __data["removeLikedByIDs"] }
    set { __data["removeLikedByIDs"] = newValue }
  }

  public var clearLikedBy: GraphQLNullable<Bool> {
    get { __data["clearLikedBy"] }
    set { __data["clearLikedBy"] = newValue }
  }

  public var addLikeIDs: GraphQLNullable<[ID]> {
    get { __data["addLikeIDs"] }
    set { __data["addLikeIDs"] = newValue }
  }

  public var removeLikeIDs: GraphQLNullable<[ID]> {
    get { __data["removeLikeIDs"] }
    set { __data["removeLikeIDs"] = newValue }
  }

  public var clearLike: GraphQLNullable<Bool> {
    get { __data["clearLike"] }
    set { __data["clearLike"] = newValue }
  }

  public var addEthnicityIDs: GraphQLNullable<[ID]> {
    get { __data["addEthnicityIDs"] }
    set { __data["addEthnicityIDs"] = newValue }
  }

  public var removeEthnicityIDs: GraphQLNullable<[ID]> {
    get { __data["removeEthnicityIDs"] }
    set { __data["removeEthnicityIDs"] = newValue }
  }

  public var clearEthnicity: GraphQLNullable<Bool> {
    get { __data["clearEthnicity"] }
    set { __data["clearEthnicity"] = newValue }
  }

  public var addSocialAccountIDs: GraphQLNullable<[ID]> {
    get { __data["addSocialAccountIDs"] }
    set { __data["addSocialAccountIDs"] = newValue }
  }

  public var removeSocialAccountIDs: GraphQLNullable<[ID]> {
    get { __data["removeSocialAccountIDs"] }
    set { __data["removeSocialAccountIDs"] = newValue }
  }

  public var clearSocialAccount: GraphQLNullable<Bool> {
    get { __data["clearSocialAccount"] }
    set { __data["clearSocialAccount"] = newValue }
  }

  public var addLifePhotoIDs: GraphQLNullable<[ID]> {
    get { __data["addLifePhotoIDs"] }
    set { __data["addLifePhotoIDs"] = newValue }
  }

  public var removeLifePhotoIDs: GraphQLNullable<[ID]> {
    get { __data["removeLifePhotoIDs"] }
    set { __data["removeLifePhotoIDs"] = newValue }
  }

  public var clearLifePhoto: GraphQLNullable<Bool> {
    get { __data["clearLifePhoto"] }
    set { __data["clearLifePhoto"] = newValue }
  }
}
