disabled_rules:
  - statement_position
  - unused_setter_value
  - notification_center_detachment
  - large_tuple
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure
  - void_return
  - trailing_whitespace

included:
  - FingerCrossed
excluded:

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
line_length: 110
function_body_length:
  warning: 120
  error: 400
type_body_length:
  warning: 500
  error: 1200
file_length:
  warning: 900
  error: 1600
type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
identifier_name:
  min_length: 2
  excluded: # excluded via string array
    - id
    - URL
    - url
    - x
    - y
    - i
    - j
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
