name: FingerCrossed
options:
  bundleIdPrefix: FingerCrossed
  deploymentTarget:
    iOS: "16.0"

targets:
  FingerCrossed:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    info:
      path: FingerCrossed/Info.plist
      properties:
        UISupportedInterfaceOrientations~iphone:
          [UIInterfaceOrientationPortrait]
        UILaunchScreen: [UILaunchScreen: []]
        UIStatusBarStyle: "UIStatusBarStyleLightContent"
        UIViewControllerBasedStatusBarAppearance: true
        UIRequiresFullScreen: true

    sources:
      - FingerCrossed
