name: FingerCrossed

options:
  bundleIdPrefix: com.FingerCrossed
  deploymentTarget:
    iOS: "16.0"

settings:
  DEVELOPMENT_TEAM: 95584NT66H

# Import package
packages:
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: 7.0.0
  facebook-ios-sdk:
    url: https://github.com/facebook/facebook-ios-sdk
    from: 16.0.0
  lottie-spm:
    url: https://github.com/airbnb/lottie-spm
    from: 4.2.0
  apollo-ios:
    url: https://github.com/apollographql/apollo-ios
    from: 1.1.3
  JWTDecode:
    url: https://github.com/auth0/JWTDecode.swift
    from: 3.0.0
  keychain-swift:
    url: https://github.com/evgenyneu/keychain-swift.git
    from: 20.0.0
  GraphQLAPI:
    path: ./GraphQL/GraphQLAPI

targets:
  FingerCrossed:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: FingerCrossed
    entitlements:
      path: FingerCrossed/FingerCrossed.entitlements
      properties:
        com.apple.developer.applesignin: ["Default"]
        keychain-access-groups:
          ["$(AppIdentifierPrefix)com.FingerCrossed.FingerCrossed"]
    info:
      path: FingerCrossed/Info.plist
      properties:
        UISupportedInterfaceOrientations~iphone:
          [UIInterfaceOrientationPortrait]
        UILaunchScreen: [UILaunchScreen: []]
        UIStatusBarStyle: "UIStatusBarStyleLightContent"
        UIViewControllerBasedStatusBarAppearance: true
        UIRequiresFullScreen: true
        NSCameraUsageDescription: "Finger Crossed needs access to your camera so you can take photos."
        NSPhotoLibraryUsageDescription: "Finger Crossed needs access to your photo library so you can share photos."
        PHPhotoLibraryPreventAutomaticLimitedAccessAlert: true
        NSMicrophoneUsageDescription: "Finger Crossed needs access to your microphone so you can record voice messages."
        NSLocationWhenInUseUsageDescription: "Finger Crossed needs access to your location to show you who's around."
        GIDClientID: "796251774309-qoqun0ovm6ttv6adjs9jdjll0ug9qsi8.apps.googleusercontent.com"
        FacebookAppID: "1204276926902380"
        FacebookClientToken: "f9fe041bf6d59db32221a5a7a9ed31ca"
        FacebookDisplayName: "Finger Crossed"
        FacebookAdvertiserIDCollectionEnabled: false
        CFBundleURLTypes:
          [
            CFBundleURLSchemes:
              [
                "com.googleusercontent.apps.796251774309-qoqun0ovm6ttv6adjs9jdjll0ug9qsi8",
                "fb1204276926902380",
              ],
          ]
        LSApplicationQueriesSchemes: [
            "fbapi", 
            "fbapi20130214", 
            "fbapi20130410", 
            "fbapi20130702", 
            "fbapi20131010", 
            "fbapi20131219", 
            "fbapi20140116",
            "fbapi20140410",
            "fbapi20150313", 
            "fbapi20150629",
            "fbapi20160328", 
            "fb-messenger-share-api", 
            "fbauth", 
            "fbauth2",
            "fbshareextension"
          ]
    dependencies:
      # specify the pacakge used in target
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: GoogleSignIn
        product: GoogleSignInSwift
      - package: facebook-ios-sdk
        product: FacebookCore
        product: FacebookLogin
      - package: lottie-spm
        product: Lottie
      - package: apollo-ios
        product: Apollo
      - package: GraphQLAPI
      - package: JWTDecode
        product: JWTDecode
      - package: keychain-swift
        product: KeychainSwift
      
    postCompileScripts:
      - script: |
          export PATH="$PATH:/opt/homebrew/bin"
          if which swiftlint >/dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        name: Swift Lint