name: FingerCrossed

options:
  bundleIdPrefix: com.FingerCrossed
  deploymentTarget:
    iOS: "16.0"

settings:
  DEVELOPMENT_TEAM: 95584NT66H

# Import package
packages:
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    exactVersion: 7.0.0
  facebook-ios-sdk:
    url: https://github.com/facebook/facebook-ios-sdk
    exactVersion: 16.1.0
  lottie-spm:
    url: https://github.com/airbnb/lottie-spm
    exactVersion: 4.2.0
  apollo-ios:
    url: https://github.com/apollographql/apollo-ios
    exactVersion: 1.1.3

  GraphQLAPI:
    path: ./GraphQL/GraphQLAPI

targets:
  FingerCrossed:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: FingerCrossed
    entitlements:
      path: FingerCrossed/FingerCrossed.entitlements
      properties:
        com.apple.developer.applesignin: ["Default"]
        keychain-access-groups:
          ["$(AppIdentifierPrefix)com.FingerCrossed.FingerCrossed"]
    info:
      path: FingerCrossed/Info.plist
      properties:
        UISupportedInterfaceOrientations~iphone:
          [UIInterfaceOrientationPortrait]
        UILaunchScreen: [UILaunchScreen: []]
        UIStatusBarStyle: "UIStatusBarStyleLightContent"
        UIViewControllerBasedStatusBarAppearance: true
        UIRequiresFullScreen: true
        NSCameraUsageDescription: "Access to the camera to take photo"
        NSPhotoLibraryUsageDescription: "Access to the photo library"
        NSMicrophoneUsageDescription: "Finger Crossed needs access to your microphone so that you can record voice message."
        NSLocationWhenInUseUsageDescription: "Access to your location"
        GIDClientID: "796251774309-qoqun0ovm6ttv6adjs9jdjll0ug9qsi8.apps.googleusercontent.com"
        FacebookAppID: "1204276926902380"
        FacebookClientToken: "f9fe041bf6d59db32221a5a7a9ed31ca"
        FacebookDisplayName: "Finger Crossed"
        FacebookAdvertiserIDCollectionEnabled: false
        CFBundleURLTypes:
          [
            CFBundleURLSchemes:
              [
                "com.googleusercontent.apps.796251774309-qoqun0ovm6ttv6adjs9jdjll0ug9qsi8",
                "fb1204276926902380",
              ],
          ]
        LSApplicationQueriesSchemes: ["fbapi", "fb-messenger-share-api"]
    dependencies:
      # specify the pacakge used in target
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: GoogleSignIn
        product: GoogleSignInSwift
      - package: facebook-ios-sdk
        product: FacebookCore
        product: FacebookLogin
      - package: lottie-spm
        product: Lottie
      - package: apollo-ios
        product: Apollo
      - package: GraphQLAPI
    postCompileScripts:
      - script: |
          export PATH="$PATH:/opt/homebrew/bin"
          if which swiftlint >/dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        name: Swift Lint